# -------------------- Install and configure Jenkins --------------------

- name: Install and configure Jenkins
  hosts: jenkins_server            #jenkins_servers group from the inventory file.
  become: yes                       #Run tasks with elevated privileges (root)
  become_method: sudo               #Specifies using sudo for privilege escalation
  become_user: root                 

  tasks:
    - name: Install Java 17 (OpenJDK)  # Jenkins requires Java 17+
      apt:
        name: openjdk-17-jdk
        state: present                 #Ensures Java is installed
        update_cache: yes              #Updates the package list before installing.

    - name: Install required dependencies for Jenkins  # Essential packages for Jenkins
      apt:
        name: "{{ item }}"
        state: present 
      loop:                                #Run the task for each item in the list
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Download Jenkins GPG key      #Securely downloads the Jenkins repository key.
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins repository        #Adds Jenkins' official repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Install Jenkins  # Installs Jenkins package
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start and enable Jenkins service  # Ensures Jenkins runs on boot
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Get the Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password
      changed_when: false
      ignore_errors: yes

    - name: Display Jenkins initial admin password (if available)
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_admin_password.stdout | default('Not found. Jenkins might be configured already.') }}"


# -------------------- Install Docker --------------------

- name: Install Docker
  hosts: jenkins_server
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install Docker dependencies  # Required dependencies for Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key  # Adds Docker security key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker repository  # Adds Docker repo to the system
      shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install Docker  # Installs Docker package
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start and enable Docker service  # Ensures Docker runs on boot
      service:
        name: docker
        state: started
        enabled: yes

# -------------------- Install kubectl --------------------

- name: Install kubectl
  hosts: jenkins_server
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Download and install kubectl  # Installs the Kubernetes CLI tool
      get_url:
        url: "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'

# -------------------- Verify Jenkins, Docker, and kubectl --------------------

- name: Verify Jenkins, Docker, and kubectl
  hosts: all
  become: yes

  tasks:
    # Check Docker Version
    - name: Check Docker Version
      command: docker --version
      register: docker_version
      changed_when: false

    - debug:
        msg: "Docker Installed: {{ docker_version.stdout }}"

    # Check if Docker Service is Running
    - name: Check if Docker Service is Running
      systemd:
        name: docker
        state: started
      register: docker_status

    - debug:
        msg: "Docker Service is {{ docker_status.status.ActiveState }}"

    # Check kubectl Version
    - name: Check kubectl Version
      command: kubectl version --client
      register: kubectl_version
      changed_when: false

    - debug:
        msg: "kubectl Installed: {{ kubectl_version.stdout }}"

    # Check if Jenkins is Running
    - name: Check if Jenkins Service is Running
      systemd:
        name: jenkins
        state: started
      register: jenkins_status

    - debug:
        msg: "Jenkins Service is {{ jenkins_status.status.ActiveState }}"

    # Get Jenkins Initial Admin Password (if needed)
    - name: Get Jenkins Initial Admin Password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password
      changed_when: false
      ignore_errors: yes  # In case it's already configured

    - debug:
        msg: "Jenkins Initial Admin Password: {{ jenkins_admin_password.stdout }}"
      when: jenkins_admin_password.stdout is defined

